version: '3'
services:
  web:
    image: <AWS-account-Id>.dkr.ecr.ap-south-1.amazonaws.com/jenkins-cicd:latest
    ports:
      - "5000:5000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: ec2-tutorial
        awslogs-region: ap-south-1
        awslogs-stream-prefix: web
